# Generated by Django 5.0.6 on 2024-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
