# Generated by Django 5.0.6 on 2024-07-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Línea Pedido', 'verbose_name_plural': 'Líneas Pedidos'},
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.AlterModelTable(
            name='lineapedido',
            table='lineapedidos',
        ),
    ]
